services:
  traefik:
    # image: traefik:2.9
    build:
      dockerfile: Dockerfile.dev
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--accesslog"
      # - "--accesslog.filepath=/var/log/traefik/access.log"
      # - --accesslog.format=json
      - --accesslog.fields.defaultmode=keep
      - --accesslog.fields.names.ClientUsername=drop
      - --accesslog.fields.headers.defaultmode=keep
      - --accesslog.fields.headers.names.User-Agent=redact
      - --accesslog.fields.headers.names.Authorization=drop
      - --accesslog.fields.headers.names.Content-Type=keep
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

      - "--experimental.localPlugins.traefik-cf-device-detector.modulename=github.com/davewhit3/traefik-cf-device-detector"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - logs-local:/var/log/traefik
      - .:/app

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.cfdevicedetect.plugin.traefik-cf-device-detector.autodetect=true"

      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.middlewares=cfdevicedetect@docker"
      - "traefik.http.routers.whoami.entrypoints=web"

volumes:
  logs-local: